name: NewWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  coluna:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install GLPK
      run: sudo apt-get install glpk-utils libglpk-dev

    - uses: julia-actions/setup-julia@latest

    - name: Install JuMP and coluna
      run: julia -e 'using Pkg; Pkg.add("JuMP"); Pkg.add("BlockDecomposition"); Pkg.add("GLPK"); Pkg.add("Coluna"); Pkg.add("DelimitedFiles")'

    - name: Solve instances with coluna
      run: ./run_coluna.sh ./GAP/data/dummies

    - uses: actions/upload-artifact@v3
      with:
        name: results
        path: results_GAP_coluna.csv

  idol:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arguments:
          - "external"
          - "bab true"
          - "bab false"
          - "bap true 0 false true"
          - "bap true 0 false false"
          - "bap true 0 true true"
          - "bap true .3 false true"
          - "bap true .8 false true"
    steps:
    - uses: actions/checkout@v3

    - name: Install GLPK
      run: sudo apt-get install glpk-utils libglpk-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-debug --config ${{env.BUILD_TYPE}}

    - name: Solve instances with idol
      run: ./run_idol.sh ./GAP/data/dummies ${{ matrix.arguments }}

    - name: Rename results file
      run: mv results_GAP_idol.csv results_GAP_idol__$(uuidgen).csv

    - uses: actions/upload-artifact@v3
      with:
        name: results
        path: results_GAP_idol__*.csv

  render:
    runs-on: ubuntu-latest
    needs: [coluna, idol]
    steps:
      - uses: actions/checkout@v3

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: results

      - name: Collect all results from idol
        run: cat results_GAP_idol__*.csv > results_GAP_idol.csv

      # Install all R markdown dependecies
      - name: Install dependencies of kableExtra
        run: sudo apt-get install libxml2-dev libfontconfig1-dev libcurl4-openssl-dev
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Install rmarkdown
        run: R -e "install.packages(\"rmarkdown\")"
      - name: Install kableExtra
        run: R -e "install.packages(\"kableExtra\")"
      - name: Install tidyr
        run: R -e "install.packages(\"tidyr\")"

      - name: Render report
        run: ./build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/
          force_orphan: true
